### ISSUE TITLE
Types are erronous in 5.0.1

### ISSUE THREAD

**Issue by jdalrymple** [jdalrymple/node-gitlab#321]
**Description**

Proper continuation of the conversation in #312

**Comment by jdalrymple** [comment]
@casz Did you find other examples we could go off of ?

**Comment by jdalrymple** [comment]
There must be a better way then:

1. Include a triple slash reference everywhere
2. Inline all the types
- Difficult because alot of the ID types are used across services
- Where would the global override types go?
3. Import all the types in every file
- Becomes quite a bit of extra boilerplate code

Unless I'm missing something :'(

**Comment by mseyma** [comment]
@jdalrymple is there anything I need to do on my end other than `npm install gitlab` and `import {gitlab} from "gitlab";?

I'm getting a lot of these errors in my sample project after updating to v5+
```node_modules/gitlab/dist/templates/ResourceVariables.d.ts(9,60): error TS2304: Cannot find name 'PaginatedRequestOptions'.```

and I'm out of ideas on how to fix (or what I'm doing worng) 😞

**Comment by jdalrymple** [comment]
Nope there is an error with the build. Still trying to figure out what's going on. Discussion is in #329
